"""
Seed script to insert common foods with accurate nutritional data per 100g serving.
Run: python seed_foods.py
"""

import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from sqlmodel import Session, select
from app.core.database import engine, create_db_and_tables
from app.models.food import Food

# Nutritional data per 100g serving (approximate USDA values)
COMMON_FOODS = [
    {
        "name": "Chicken Breast",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 165.0,
        "protein_g": 31.0,
        "carbs_g": 0.0,
        "fat_g": 3.6,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "is_verified": True,
    },
    {
        "name": "White Rice (cooked)",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 130.0,
        "protein_g": 2.7,
        "carbs_g": 28.2,
        "fat_g": 0.3,
        "fiber_g": 0.4,
        "sugar_g": 0.0,
        "is_verified": True,
    },
    {
        "name": "Whole Eggs",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 155.0,
        "protein_g": 13.0,
        "carbs_g": 1.1,
        "fat_g": 11.0,
        "fiber_g": 0.0,
        "sugar_g": 1.1,
        "is_verified": True,
    },
    {
        "name": "Banana",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 89.0,
        "protein_g": 1.1,
        "carbs_g": 22.8,
        "fat_g": 0.3,
        "fiber_g": 2.6,
        "sugar_g": 12.2,
        "is_verified": True,
    },
    {
        "name": "Oatmeal (dry)",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 389.0,
        "protein_g": 16.9,
        "carbs_g": 66.3,
        "fat_g": 6.9,
        "fiber_g": 10.6,
        "sugar_g": 0.0,
        "is_verified": True,
    },
    {
        "name": "Salmon (Atlantic, cooked)",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 208.0,
        "protein_g": 20.4,
        "carbs_g": 0.0,
        "fat_g": 13.4,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "is_verified": True,
    },
    {
        "name": "Broccoli",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 34.0,
        "protein_g": 2.8,
        "carbs_g": 6.6,
        "fat_g": 0.4,
        "fiber_g": 2.6,
        "sugar_g": 1.7,
        "is_verified": True,
    },
    {
        "name": "Sweet Potato (cooked)",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 86.0,
        "protein_g": 1.6,
        "carbs_g": 20.1,
        "fat_g": 0.1,
        "fiber_g": 3.0,
        "sugar_g": 4.2,
        "is_verified": True,
    },
    {
        "name": "Greek Yogurt (plain, nonfat)",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 59.0,
        "protein_g": 10.2,
        "carbs_g": 3.6,
        "fat_g": 0.4,
        "fiber_g": 0.0,
        "sugar_g": 3.2,
        "is_verified": True,
    },
    {
        "name": "Almonds",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 579.0,
        "protein_g": 21.2,
        "carbs_g": 21.6,
        "fat_g": 49.9,
        "fiber_g": 12.5,
        "sugar_g": 4.4,
        "is_verified": True,
    },
    {
        "name": "Avocado",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 160.0,
        "protein_g": 2.0,
        "carbs_g": 8.5,
        "fat_g": 14.7,
        "fiber_g": 6.7,
        "sugar_g": 0.7,
        "is_verified": True,
    },
    {
        "name": "Whole Milk",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "calories": 61.0,
        "protein_g": 3.2,
        "carbs_g": 4.8,
        "fat_g": 3.3,
        "fiber_g": 0.0,
        "sugar_g": 5.0,
        "is_verified": True,
    },
    {
        "name": "Whole Wheat Bread",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 247.0,
        "protein_g": 13.0,
        "carbs_g": 41.3,
        "fat_g": 3.4,
        "fiber_g": 6.0,
        "sugar_g": 5.6,
        "is_verified": True,
    },
    {
        "name": "Pasta (cooked)",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 131.0,
        "protein_g": 5.0,
        "carbs_g": 25.0,
        "fat_g": 1.1,
        "fiber_g": 1.8,
        "sugar_g": 0.6,
        "is_verified": True,
    },
    {
        "name": "Apple",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 52.0,
        "protein_g": 0.3,
        "carbs_g": 13.8,
        "fat_g": 0.2,
        "fiber_g": 2.4,
        "sugar_g": 10.4,
        "is_verified": True,
    },
    {
        "name": "Orange",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 47.0,
        "protein_g": 0.9,
        "carbs_g": 11.8,
        "fat_g": 0.1,
        "fiber_g": 2.4,
        "sugar_g": 9.4,
        "is_verified": True,
    },
    {
        "name": "Ground Beef (85% lean)",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 250.0,
        "protein_g": 26.1,
        "carbs_g": 0.0,
        "fat_g": 15.0,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "is_verified": True,
    },
    {
        "name": "Tuna (canned in water)",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 116.0,
        "protein_g": 25.5,
        "carbs_g": 0.0,
        "fat_g": 0.8,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "is_verified": True,
    },
    {
        "name": "Spinach (raw)",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 23.0,
        "protein_g": 2.9,
        "carbs_g": 3.6,
        "fat_g": 0.4,
        "fiber_g": 2.2,
        "sugar_g": 0.4,
        "is_verified": True,
    },
    {
        "name": "Olive Oil",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "ml",
        "calories": 884.0,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fat_g": 100.0,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "is_verified": True,
    },
    {
        "name": "Peanut Butter",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 588.0,
        "protein_g": 25.1,
        "carbs_g": 20.0,
        "fat_g": 50.4,
        "fiber_g": 6.0,
        "sugar_g": 9.2,
        "is_verified": True,
    },
    {
        "name": "Brown Rice (cooked)",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 111.0,
        "protein_g": 2.6,
        "carbs_g": 23.0,
        "fat_g": 0.9,
        "fiber_g": 1.8,
        "sugar_g": 0.4,
        "is_verified": True,
    },
    {
        "name": "Cottage Cheese (low fat)",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 72.0,
        "protein_g": 12.4,
        "carbs_g": 2.7,
        "fat_g": 1.0,
        "fiber_g": 0.0,
        "sugar_g": 2.7,
        "is_verified": True,
    },
    {
        "name": "Whey Protein Powder",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 375.0,
        "protein_g": 78.0,
        "carbs_g": 9.0,
        "fat_g": 3.0,
        "fiber_g": 0.0,
        "sugar_g": 3.0,
        "is_verified": True,
    },
    {
        "name": "Turkey Breast",
        "brand": "Generic",
        "serving_size": 100.0,
        "serving_unit": "g",
        "calories": 135.0,
        "protein_g": 30.0,
        "carbs_g": 0.0,
        "fat_g": 1.0,
        "fiber_g": 0.0,
        "sugar_g": 0.0,
        "is_verified": True,
    },
]


def seed_foods():
    create_db_and_tables()

    with Session(engine) as session:
        # Check if foods already exist
        existing = session.exec(select(Food)).first()
        if existing:
            print(f"Foods table already has data. Skipping seed.")
            return

        for food_data in COMMON_FOODS:
            food = Food(**food_data)
            session.add(food)

        session.commit()
        print(f"Successfully seeded {len(COMMON_FOODS)} foods into the database.")


if __name__ == "__main__":
    seed_foods()
