#!/usr/bin/env python3
"""
Fitsi IA — Capacity Report Analyzer
════════════════════════════════════

Analyzes stress test results and generates infrastructure recommendations.

Usage:
    cd backend/
    python scripts/capacity_report.py results/stress_test_YYYYMMDD_HHMMSS/full_report.json
    python scripts/capacity_report.py results/stress_test_YYYYMMDD_HHMMSS/full_report.json --output report.md

Input: full_report.json generated by run_stress_test.sh
Output: Console report + optional file output
"""

import argparse
import json
import math
import sys
from dataclasses import dataclass
from pathlib import Path


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class PhaseResult:
    phase: int
    name: str
    target_users: int
    spawn_rate: int
    duration: str
    actual_duration_s: int
    total_requests: int
    total_failures: int
    error_rate_pct: float
    rps: float
    avg_latency_ms: float
    p50_latency_ms: float
    p95_latency_ms: float
    p99_latency_ms: float
    survived: bool
    exit_code: int


@dataclass
class CapacityAnalysis:
    breaking_point_users: int
    breaking_point_phase: str
    max_sustained_rps: float
    max_stable_users: int
    max_stable_phase: str
    degradation_start_users: int
    degradation_start_phase: str
    bottlenecks: list
    recommendations: dict
    infrastructure: dict
    cost_estimates: dict


# ---------------------------------------------------------------------------
# Thresholds for analysis
# ---------------------------------------------------------------------------

# When we consider the system "degraded"
MAX_ACCEPTABLE_P95_MS = 2000       # 2 seconds
MAX_ACCEPTABLE_P99_MS = 5000       # 5 seconds
MAX_ACCEPTABLE_ERROR_RATE = 5.0    # 5%
MIN_ACCEPTABLE_RPS_RATIO = 0.5     # Must sustain at least 50% of expected RPS

# Infrastructure sizing constants (per 1000 concurrent users)
USERS_PER_WORKER = 250            # Each uvicorn/gunicorn worker handles ~250 concurrent
RAM_PER_WORKER_MB = 256           # Each worker uses ~256MB
DB_CONNECTIONS_PER_WORKER = 10    # Each worker holds ~10 DB connections
REDIS_MEM_PER_1K_USERS_MB = 50   # Redis cache per 1000 users


# ---------------------------------------------------------------------------
# Analysis functions
# ---------------------------------------------------------------------------

def load_report(path: str) -> list[PhaseResult]:
    """Load and parse the full_report.json."""
    with open(path) as f:
        data = json.load(f)

    phases = []
    for p in data.get("phases", []):
        phases.append(PhaseResult(
            phase=int(p.get("phase", 0)),
            name=str(p.get("name", "")),
            target_users=int(p.get("target_users", 0)),
            spawn_rate=int(p.get("spawn_rate", 0)),
            duration=str(p.get("duration", "")),
            actual_duration_s=int(p.get("actual_duration_s", 0)),
            total_requests=int(p.get("total_requests", 0)),
            total_failures=int(p.get("total_failures", 0)),
            error_rate_pct=float(p.get("error_rate_pct", 0)),
            rps=float(p.get("rps", 0)),
            avg_latency_ms=float(p.get("avg_latency_ms", 0)),
            p50_latency_ms=float(p.get("p50_latency_ms", 0)),
            p95_latency_ms=float(p.get("p95_latency_ms", 0)),
            p99_latency_ms=float(p.get("p99_latency_ms", 0)),
            survived=bool(p.get("survived", False)),
            exit_code=int(p.get("exit_code", 0)),
        ))

    return sorted(phases, key=lambda x: x.phase)


def analyze(phases: list[PhaseResult]) -> CapacityAnalysis:
    """Perform capacity analysis on phase results."""

    if not phases:
        return CapacityAnalysis(
            breaking_point_users=0, breaking_point_phase="N/A",
            max_sustained_rps=0, max_stable_users=0, max_stable_phase="N/A",
            degradation_start_users=0, degradation_start_phase="N/A",
            bottlenecks=["No data"], recommendations={},
            infrastructure={}, cost_estimates={},
        )

    # Find breaking point (first phase that didn't survive or had >50% error rate)
    breaking_point = None
    for p in phases:
        if not p.survived or p.error_rate_pct > 50:
            breaking_point = p
            break

    # Find degradation start (first phase exceeding thresholds)
    degradation_start = None
    for p in phases:
        if (p.p95_latency_ms > MAX_ACCEPTABLE_P95_MS
                or p.error_rate_pct > MAX_ACCEPTABLE_ERROR_RATE):
            degradation_start = p
            break

    # Find max stable phase (last phase within acceptable thresholds)
    max_stable = phases[0]
    for p in phases:
        if (p.survived
                and p.p95_latency_ms <= MAX_ACCEPTABLE_P95_MS
                and p.error_rate_pct <= MAX_ACCEPTABLE_ERROR_RATE):
            max_stable = p

    # Max sustained RPS (highest RPS from a stable phase)
    max_rps = 0.0
    for p in phases:
        if p.survived and p.error_rate_pct <= MAX_ACCEPTABLE_ERROR_RATE:
            max_rps = max(max_rps, p.rps)

    # Identify bottlenecks
    bottlenecks = _identify_bottlenecks(phases)

    # Infrastructure recommendations
    infra = _calc_infrastructure(phases)

    # Cost estimates
    costs = _estimate_costs(infra)

    # General recommendations
    recs = _generate_recommendations(phases, bottlenecks, max_stable)

    return CapacityAnalysis(
        breaking_point_users=breaking_point.target_users if breaking_point else 0,
        breaking_point_phase=breaking_point.name if breaking_point else "None (all survived)",
        max_sustained_rps=max_rps,
        max_stable_users=max_stable.target_users,
        max_stable_phase=max_stable.name,
        degradation_start_users=degradation_start.target_users if degradation_start else 0,
        degradation_start_phase=degradation_start.name if degradation_start else "None",
        bottlenecks=bottlenecks,
        recommendations=recs,
        infrastructure=infra,
        cost_estimates=costs,
    )


def _identify_bottlenecks(phases: list[PhaseResult]) -> list[str]:
    """Identify likely bottlenecks from phase metrics."""
    bottlenecks = []

    for i, p in enumerate(phases):
        if i == 0:
            continue

        prev = phases[i - 1]

        # Latency spike: p95 more than doubled
        if prev.p95_latency_ms > 0 and p.p95_latency_ms > prev.p95_latency_ms * 2:
            bottlenecks.append(
                f"Latency spike at {p.target_users} users: "
                f"p95 went from {prev.p95_latency_ms:.0f}ms to {p.p95_latency_ms:.0f}ms "
                f"(likely DB connection pool exhaustion or CPU saturation)"
            )

        # RPS plateau: RPS didn't scale with users
        if prev.rps > 0:
            user_ratio = p.target_users / prev.target_users
            rps_ratio = p.rps / prev.rps if prev.rps > 0 else 0
            if rps_ratio < user_ratio * 0.3 and p.target_users >= 1000:
                bottlenecks.append(
                    f"RPS plateau at {p.target_users} users: "
                    f"users grew {user_ratio:.0f}x but RPS only grew {rps_ratio:.1f}x "
                    f"(server cannot accept more concurrent connections)"
                )

        # Error spike
        if p.error_rate_pct > MAX_ACCEPTABLE_ERROR_RATE and prev.error_rate_pct <= MAX_ACCEPTABLE_ERROR_RATE:
            bottlenecks.append(
                f"Error rate crossed threshold at {p.target_users} users: "
                f"{p.error_rate_pct:.1f}% (likely connection timeouts or worker exhaustion)"
            )

        # Memory pressure indicator: avg latency >> p50 (long tail)
        if p.p50_latency_ms > 0 and p.avg_latency_ms > p.p50_latency_ms * 3:
            bottlenecks.append(
                f"Long tail latency at {p.target_users} users: "
                f"avg={p.avg_latency_ms:.0f}ms vs p50={p.p50_latency_ms:.0f}ms "
                f"(possible GC pauses, swap, or lock contention)"
            )

    if not bottlenecks:
        bottlenecks.append("No significant bottlenecks detected in the tested range")

    return bottlenecks


def _calc_infrastructure(phases: list[PhaseResult]) -> dict:
    """Calculate infrastructure requirements for each user tier."""
    tiers = {
        "10K": 10_000,
        "50K": 50_000,
        "100K": 100_000,
        "200K": 200_000,
    }

    infra = {}
    for tier_name, users in tiers.items():
        workers = math.ceil(users / USERS_PER_WORKER)
        # Distribute workers across server instances (max 8 workers per server)
        workers_per_server = 8
        servers = math.ceil(workers / workers_per_server)
        ram_per_server_gb = math.ceil((workers_per_server * RAM_PER_WORKER_MB) / 1024)
        db_connections = workers * DB_CONNECTIONS_PER_WORKER
        redis_mb = math.ceil(users / 1000 * REDIS_MEM_PER_1K_USERS_MB)

        # CPU: assume 2 vCPU per 4 workers (IO-bound FastAPI)
        vcpu_per_server = math.ceil(workers_per_server / 2)

        infra[tier_name] = {
            "concurrent_users": users,
            "total_workers": workers,
            "app_servers": servers,
            "vcpu_per_server": max(vcpu_per_server, 2),
            "ram_per_server_gb": max(ram_per_server_gb, 4),
            "total_ram_gb": servers * max(ram_per_server_gb, 4),
            "db_pool_size": db_connections,
            "db_server_type": _db_tier(db_connections),
            "redis_memory_mb": redis_mb,
            "redis_server_type": _redis_tier(redis_mb),
            "load_balancer": "ALB" if servers > 1 else "None (single server)",
            "cdn_recommended": users >= 50_000,
        }

    return infra


def _db_tier(connections: int) -> str:
    """Recommend a PostgreSQL instance type based on connection count."""
    if connections <= 100:
        return "db.t3.medium (2 vCPU, 4GB) — RDS"
    elif connections <= 400:
        return "db.r6g.large (2 vCPU, 16GB) — RDS"
    elif connections <= 1000:
        return "db.r6g.xlarge (4 vCPU, 32GB) — RDS"
    elif connections <= 2000:
        return "db.r6g.2xlarge (8 vCPU, 64GB) — RDS"
    else:
        return "db.r6g.4xlarge (16 vCPU, 128GB) — RDS + read replicas"


def _redis_tier(memory_mb: int) -> str:
    """Recommend a Redis instance type based on memory needs."""
    if memory_mb <= 500:
        return "cache.t3.small (1.5GB)"
    elif memory_mb <= 2000:
        return "cache.r6g.large (13GB)"
    elif memory_mb <= 6000:
        return "cache.r6g.xlarge (26GB)"
    else:
        return "cache.r6g.2xlarge (52GB) — ElastiCache cluster"


def _estimate_costs(infra: dict) -> dict:
    """Estimate monthly AWS costs for each tier."""
    # Approximate AWS pricing (us-east-1, on-demand, monthly)
    costs = {}

    pricing = {
        "app_server_per_vcpu": 35,     # ~$35/mo per vCPU (c6g instances)
        "app_server_per_gb_ram": 5,    # ~$5/mo per GB RAM
        "rds_per_connection_approx": 0.5,  # rough proxy
        "redis_per_gb": 25,            # ~$25/mo per GB (ElastiCache)
        "alb_base": 25,               # ALB fixed cost
        "alb_per_lcu": 8,             # per LCU-hour
        "cloudfront_per_tb": 85,       # per TB transfer
        "monitoring": 50,              # CloudWatch, alarms
    }

    for tier_name, spec in infra.items():
        servers = spec["app_servers"]
        vcpu = spec["vcpu_per_server"]
        ram = spec["ram_per_server_gb"]

        compute = servers * (vcpu * pricing["app_server_per_vcpu"]
                             + ram * pricing["app_server_per_gb_ram"])
        db = spec["db_pool_size"] * pricing["rds_per_connection_approx"]
        redis = (spec["redis_memory_mb"] / 1024) * pricing["redis_per_gb"]
        lb = pricing["alb_base"] + pricing["alb_per_lcu"] if servers > 1 else 0
        cdn = pricing["cloudfront_per_tb"] if spec["cdn_recommended"] else 0
        monitoring = pricing["monitoring"]

        total = compute + db + redis + lb + cdn + monitoring

        costs[tier_name] = {
            "compute": round(compute),
            "database": round(db),
            "redis": round(redis),
            "load_balancer": round(lb),
            "cdn": round(cdn),
            "monitoring": round(monitoring),
            "total_monthly_usd": round(total),
        }

    return costs


def _generate_recommendations(
    phases: list[PhaseResult],
    bottlenecks: list[str],
    max_stable: PhaseResult,
) -> dict:
    """Generate actionable recommendations."""
    recs = {
        "immediate": [],
        "short_term": [],
        "long_term": [],
    }

    # Based on max stable load
    if max_stable.target_users < 1000:
        recs["immediate"].append(
            "Critical: System cannot handle 1K users. "
            "Increase Gunicorn workers (workers = CPU * 2 + 1), "
            "enable connection pooling (pgbouncer), and add Redis caching."
        )
    elif max_stable.target_users < 10000:
        recs["immediate"].append(
            "System handles <10K users. Scale horizontally: "
            "deploy behind a load balancer with 2-4 app servers."
        )

    # Latency recommendations
    if max_stable.p95_latency_ms > 500:
        recs["short_term"].append(
            f"p95 latency is {max_stable.p95_latency_ms:.0f}ms even at stable load. "
            "Add database query caching (Redis), optimize N+1 queries, "
            "and ensure proper DB indexes on user_id + date columns."
        )

    # Based on bottlenecks
    for b in bottlenecks:
        if "connection pool" in b.lower():
            recs["short_term"].append(
                "DB connection pool exhaustion detected. "
                "Deploy PgBouncer (transaction mode) between app and PostgreSQL. "
                "Set pool_size=20, max_overflow=30 per worker."
            )
        if "rps plateau" in b.lower():
            recs["short_term"].append(
                "RPS plateau detected — server is saturated. "
                "Add horizontal scaling with auto-scaling groups. "
                "Target: scale up when CPU > 70% for 2 minutes."
            )
        if "gc pauses" in b.lower() or "long tail" in b.lower():
            recs["short_term"].append(
                "Long-tail latency (GC/memory pressure). "
                "Enable max_requests=2000 in Gunicorn to recycle workers, "
                "and increase per-worker memory allocation."
            )

    # General scaling recommendations
    recs["long_term"].extend([
        "Implement read replicas for PostgreSQL (1 writer + 2 readers) "
        "to offload GET endpoints (dashboard, food logs, profile).",
        "Move AI food scanning to async Celery workers "
        "to prevent blocking the main API process.",
        "Add CDN (CloudFront/Cloudflare) for static assets "
        "and consider edge caching for GET /api/dashboard/today.",
        "Implement WebSocket for real-time dashboard updates "
        "instead of polling (reduces request count by ~40%).",
        "Consider moving to Kubernetes (EKS) for auto-scaling "
        "with HPA based on RPS and latency metrics.",
    ])

    return recs


# ---------------------------------------------------------------------------
# Report formatting
# ---------------------------------------------------------------------------

def format_report(analysis: CapacityAnalysis, phases: list[PhaseResult]) -> str:
    """Format the capacity analysis as a human-readable report."""
    lines = []
    w = lines.append

    w("=" * 78)
    w("  FITSI IA — CAPACITY ANALYSIS REPORT")
    w("=" * 78)
    w("")

    # Executive Summary
    w("1. EXECUTIVE SUMMARY")
    w("-" * 78)
    w(f"  Max stable users:      {analysis.max_stable_users:,} ({analysis.max_stable_phase})")
    w(f"  Degradation starts at: {analysis.degradation_start_users:,} ({analysis.degradation_start_phase})")
    w(f"  Breaking point:        {analysis.breaking_point_users:,} ({analysis.breaking_point_phase})")
    w(f"  Max sustained RPS:     {analysis.max_sustained_rps:,.1f} req/s")
    w("")

    # Phase Results Table
    w("2. PHASE-BY-PHASE RESULTS")
    w("-" * 78)
    header = (
        f"{'Phase':<6} {'Name':<16} {'Users':>8} {'RPS':>8} "
        f"{'p50':>8} {'p95':>8} {'p99':>8} {'Err%':>7} {'OK':>4}"
    )
    w(header)
    w("-" * len(header))

    for p in phases:
        status = "YES" if p.survived and p.error_rate_pct <= MAX_ACCEPTABLE_ERROR_RATE else "NO"
        w(
            f"{p.phase:<6} {p.name:<16} {p.target_users:>8,} {p.rps:>8.1f} "
            f"{p.p50_latency_ms:>7.0f}ms {p.p95_latency_ms:>7.0f}ms "
            f"{p.p99_latency_ms:>7.0f}ms {p.error_rate_pct:>6.1f}% {status:>4}"
        )
    w("")

    # Bottlenecks
    w("3. IDENTIFIED BOTTLENECKS")
    w("-" * 78)
    for i, b in enumerate(analysis.bottlenecks, 1):
        w(f"  {i}. {b}")
    w("")

    # Infrastructure Recommendations
    w("4. INFRASTRUCTURE REQUIREMENTS")
    w("-" * 78)
    for tier_name, spec in analysis.infrastructure.items():
        w(f"  === {tier_name} Users ({spec['concurrent_users']:,} concurrent) ===")
        w(f"    App servers:     {spec['app_servers']} x ({spec['vcpu_per_server']} vCPU, {spec['ram_per_server_gb']}GB RAM)")
        w(f"    Total workers:   {spec['total_workers']}")
        w(f"    Total RAM:       {spec['total_ram_gb']}GB")
        w(f"    DB:              {spec['db_server_type']}")
        w(f"    DB pool size:    {spec['db_pool_size']} connections")
        w(f"    Redis:           {spec['redis_server_type']} ({spec['redis_memory_mb']}MB)")
        w(f"    Load balancer:   {spec['load_balancer']}")
        w(f"    CDN:             {'Yes' if spec['cdn_recommended'] else 'Not required'}")
        w("")

    # Cost Estimates
    w("5. ESTIMATED MONTHLY COSTS (AWS, us-east-1, on-demand)")
    w("-" * 78)
    cost_header = f"{'Tier':<8} {'Compute':>10} {'DB':>8} {'Redis':>8} {'LB':>6} {'CDN':>6} {'Mon':>6} {'TOTAL':>10}"
    w(cost_header)
    w("-" * len(cost_header))
    for tier_name, cost in analysis.cost_estimates.items():
        w(
            f"{tier_name:<8} ${cost['compute']:>9,} ${cost['database']:>7,} "
            f"${cost['redis']:>7,} ${cost['load_balancer']:>5,} "
            f"${cost['cdn']:>5,} ${cost['monitoring']:>5,} ${cost['total_monthly_usd']:>9,}"
        )
    w("")
    w("  NOTE: These are rough estimates using on-demand pricing.")
    w("  Reserved instances or savings plans can reduce costs by 30-60%.")
    w("  Spot instances for non-critical workers can save an additional 50-70%.")
    w("")

    # Recommendations
    w("6. RECOMMENDATIONS")
    w("-" * 78)

    if analysis.recommendations.get("immediate"):
        w("  IMMEDIATE (do now):")
        for r in analysis.recommendations["immediate"]:
            w(f"    * {r}")
        w("")

    if analysis.recommendations.get("short_term"):
        w("  SHORT TERM (next 2-4 weeks):")
        for r in analysis.recommendations["short_term"]:
            w(f"    * {r}")
        w("")

    if analysis.recommendations.get("long_term"):
        w("  LONG TERM (next quarter):")
        for r in analysis.recommendations["long_term"]:
            w(f"    * {r}")
        w("")

    w("=" * 78)
    return "\n".join(lines)


def format_json(analysis: CapacityAnalysis, phases: list[PhaseResult]) -> str:
    """Format the analysis as JSON."""
    return json.dumps({
        "summary": {
            "max_stable_users": analysis.max_stable_users,
            "max_stable_phase": analysis.max_stable_phase,
            "degradation_start_users": analysis.degradation_start_users,
            "breaking_point_users": analysis.breaking_point_users,
            "max_sustained_rps": analysis.max_sustained_rps,
        },
        "phases": [
            {
                "phase": p.phase,
                "name": p.name,
                "users": p.target_users,
                "rps": p.rps,
                "p50_ms": p.p50_latency_ms,
                "p95_ms": p.p95_latency_ms,
                "p99_ms": p.p99_latency_ms,
                "error_rate": p.error_rate_pct,
                "survived": p.survived,
            }
            for p in phases
        ],
        "bottlenecks": analysis.bottlenecks,
        "infrastructure": analysis.infrastructure,
        "cost_estimates": analysis.cost_estimates,
        "recommendations": analysis.recommendations,
    }, indent=2)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Fitsi IA — Capacity Report Analyzer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python scripts/capacity_report.py results/stress_test_*/full_report.json
    python scripts/capacity_report.py results/full_report.json --output capacity.md
    python scripts/capacity_report.py results/full_report.json --json
        """,
    )
    parser.add_argument("report_file", help="Path to full_report.json from stress test")
    parser.add_argument("--output", "-o", help="Write report to file (default: stdout)")
    parser.add_argument("--json", action="store_true", help="Output as JSON instead of text")

    args = parser.parse_args()

    report_path = Path(args.report_file)
    if not report_path.exists():
        print(f"ERROR: Report file not found: {report_path}", file=sys.stderr)
        sys.exit(1)

    # Load and analyze
    print(f"Loading results from {report_path}...", file=sys.stderr)
    phases = load_report(str(report_path))
    print(f"Loaded {len(phases)} phases. Analyzing...", file=sys.stderr)

    analysis = analyze(phases)

    # Format output
    if args.json:
        output = format_json(analysis, phases)
    else:
        output = format_report(analysis, phases)

    # Write output
    if args.output:
        output_path = Path(args.output)
        output_path.write_text(output)
        print(f"Report written to {output_path}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
