"""Placeholder — replace this with an autogenerated migration.

This file exists as a marker so the versions/ directory is tracked by git.
To generate the real initial migration, run:

    cd backend
    alembic revision --autogenerate -m "initial"

That command will inspect your running database (make sure it's empty /
freshly created) and generate a proper upgrade/downgrade script.

Delete this file once you have run the autogenerate command.

Revision ID: 001_initial_schema
Revises:
Create Date: 2026-03-19
"""

# Run: alembic revision --autogenerate -m "initial"
#
# Prerequisites:
#   1. The database must be reachable (docker-compose up db, or local postgres).
#   2. DATABASE_URL / database_url_async must point to that database.
#   3. All model files must be imported in alembic/env.py (they already are).
#
# After generating, apply with:
#   alembic upgrade head

from typing import Sequence, Union

revision: str = "001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # This placeholder intentionally does nothing.
    # Replace this file with the autogenerated migration.
    pass


def downgrade() -> None:
    pass
